# Generated by Django 6.0.5 on 2026-08-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('P', 'Pasaporte')], default='CC', max_length=10)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('motivo_visita', models.CharField(blank=True, max_length=200)),
                ('empleado_a_visitar', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('Dentro', 'Dentro'), ('Fuera', 'Fuera')], default='En espera', max_length=15)),
                ('codigo_barras', models.CharField(blank=True, max_length=30, unique=True)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
