# Generated by Django 6.0.5 on 2026-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_asignado', models.CharField(max_length=100)),
                ('id_empleado', models.IntegerField()),
                ('area', models.CharField(choices=[('Sistemas', 'Sistemas'), ('Administración', 'Administración'), ('Coordinación', 'Coordinación'), ('Almacén', 'Almacén')], max_length=50)),
                ('tipo_equipo', models.CharField(choices=[('Portátil', 'Portátil'), ('Desktop', 'Desktop'), ('Monitor', 'Monitor'), ('Impresora', 'Impresora'), ('Tablet', 'Tablet')], max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('codigo_inventario', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
