# Generated by Django 6.0.5 on 2026-07-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
