# Generated by Django 6.0.5 on 2026-08-11 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('equipos', '0002_alter_equipo_codigo_barras'),
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(db_index=True, max_length=30)),
                ('tipo_registro', models.CharField(choices=[('Empleado', 'Empleado'), ('Visitante', 'Visitante'), ('Equipo', 'Equipo'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=15)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], default='Entrada', max_length=10)),
                ('estado', models.CharField(choices=[('Permitido', 'Permitido'), ('Denegado', 'Denegado')], default='Permitido', max_length=15)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='empleados.empleado')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='equipos.equipo')),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='visitantes.visitante')),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
